### ISSUE TITLE
Need to normalize notes into some sort of "type" code/identifier

### ISSUE THREAD

**Issue by thisismattmiller** [nypl-registry/utils-lexicon#1]
In an effort to know what type a note is in the future we need to standardize all the note types across the main systems. The current version of this is:
https://github.com/nypl-registry/utils-lexicon/blob/master/lib/labels/notes.js

But some sort of identifier/code would be better than a string.

This can live in the application layer for now being stored as a "label" on the resource object.

**Comment by saverkamp** [comment]
I think we were originally trying to avoid blank nodes, but if you think we're ready to break them out into their own objects, that works. I thought I had normalized all of those note types across all four systems, but I can take another look to shorten the list. I have no idea what some of those MARC note fields actually are.

**Comment by thisismattmiller** [comment]
I don't want to do blank nodes unless they are going into a real triple store. This code can live in the application layer data, but I thought it would be better to have a code then a long string with spaces. If you did normalize them I think I used that for this list?

**Comment by saverkamp** [comment]
Yes, that's the list, but I didn't get too deep into the semantics of each note type. If you think it wouldn't be too hard to update these mappings later, we could create codes now and punt on a more controlled list until someone has more time to look into it. It might be good to get cataloger/archivist/wallach input on that list anyway.

**Comment by thisismattmiller** [comment]
Will leave as is for now, labels will become part of the literal.
